addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
    - libglu1-mesa-dev
language: rust
rust:
  - stable
  - nightly
cache: cargo
os:
  - osx
  - linux
dist: xenial
notifications:
  webhooks: http://build.servo.org:54856/travis
env:
  - VERBOSE=1
