[package]

name = "skia-sys"
version = "0.20130412.4"
authors = ["The Skia Project Developers and The Servo Project Developers"]
description = "2D graphic library for drawing Text, Geometries, and Images. FFI bindings only."
license = "BSD-3-Clause"
repository ="https://github.com/servo/skia/"
homepage = "https://skia.org/"
links = "skia"
build = "build.rs"
exclude = [
    "experimental/*",
    "expectations/*",
    "platform_tools/android/bin/*",
    "tools/*",
    "tests/*",
]

[lib]
name = "skia_sys"

[dependencies]
libc = "0.2"
expat-sys = "2.1.0"

[target.i686-unknown-linux-gnu.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
[target.x86_64-unknown-linux-gnu.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
[target.arm-unknown-linux-gnueabihf.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
[target.aarch64-unknown-linux-gnu.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"

[target.arm-linux-androideabi.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
[target.aarch64-linux-android.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
[target.i686-linux-android.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
[target.x86_64-linux-android.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"

[target.x86_64-pc-windows-gnu.dependencies]
servo-fontconfig-sys = "2.11"
servo-freetype-sys = "2.4.11"
